# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1f8e2bc0f80805c49415056b7c52139"
application_url = "https://yea-managers-dealt-ul.trycloudflare.com"
embedded = true
name = "test-dev-app"
handle = "test-dev-app-42"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,unauthenticated_read_product_listings,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://yea-managers-dealt-ul.trycloudflare.com/auth/callback",
  "https://yea-managers-dealt-ul.trycloudflare.com/auth/shopify/callback",
  "https://yea-managers-dealt-ul.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
