# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4c6005362e093f863db4f1bb8b5dfa1"
application_url = "https://numerous-expects-husband-payment.trycloudflare.com"
embedded = true
name = "test-dev-app"
handle = "test-dev-app-41"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,unauthenticated_read_product_listings,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://numerous-expects-husband-payment.trycloudflare.com/auth/callback",
  "https://numerous-expects-husband-payment.trycloudflare.com/auth/shopify/callback",
  "https://numerous-expects-husband-payment.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
